services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WACON\Forms2db\:
    resource: '../Classes/*'
  
  WACON\Forms2db\Controller\FormsdbModuleController:
    tags: ['backend.controller']

